---
title: "HARVEST ADVICE FOR PACIFIC SARDINE (*SARDINOPS SAGAX*) IN BRITISH COLUMBIA WATERS FOR 2019 SEASON"
title_short: "Harvest Advice for \\break Pacific Sardine in BC for the 2019 Season"
title_other: "Avis sur les prélèvements de sardines du Pacifique (Sardinops sagax) dans les eaux de la Colombie-Britannique pour la saison 2019. Secr. can. de consult. sci. du MPO, Rép. des Sci. 2019/nnn."
year: 2019
month: May
report_number: nnn
approver: |
  Carmel Lowe\
  Regional Director\
  Science Branch, Pacific Region\
  Fisheries and Oceans Canada
approval_year: 2019
approval_month: May
approval_day: XX
branch: Science Branch
region: Pacific Region
address: |
  ^1^Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada
phone: (250) 756-7208
email: csap@dfo-mpo.gc.ca
output:
 csasdown::sr_pdf
  # csasdown::sr_word:
    # french: false
type:
  sr
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
lot: true
lof: true
# Any extra LaTeX code for the header:
# header-includes:
# - \usepackage{tikz}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = if (knitr:::is_latex_output()) "knitr-figs-pdf/" else "knitr-figs-docx/",
  cache.path = if (knitr:::is_latex_output()) "knitr-cache-tex/" else "knitr-cache-docx/",
  fig.asp = 0.618,
  fig.width = 9,
  out.width = "6in",
  echo = FALSE,
#  autodep = TRUE,
#  cache = TRUE,
  cache.comments = FALSE,
  dev = if (knitr:::is_latex_output()) "png" else "png",
  dpi = 180,
  fig.align = "center",
  fig.pos = "htb"
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(csasdown)
library(lubridate)
source(here::here("R", "utils.R"))

d <- readr::read_csv(here::here("data", "data.csv"))
curr_year <- year(Sys.Date())
curr_vals <- d %>% 
  filter(year == curr_year)
b <- f(curr_vals$biomass_estimate)
```
